import { SH, SW } from "../../../utils";
import { primaryColors } from "../DesignSystem/colorPalette";
import { body } from "../DesignSystem/typography";
import { Dimensions, StyleSheet } from "react-native";
const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get("window");
const DROPDOWN_HEIGHT = SCREEN_HEIGHT * 0.5;
const DROPDOWN_WIDTH = SCREEN_WIDTH * 0.7;
export const formElementsStyles = {
  triggerStyle: {
    display: "flex",
    flexDirection: "row",
    maxWidth: "100%",
    borderColor: primaryColors.gray[200],
    borderWidth: SW(1),
    borderRadius: SW(8),
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SW(14),
    paddingVertical: SH(10),
    height: SH(44),
  },
  disabledStyle: {
    backgroundColor: primaryColors.gray[50],
  },
  titleStyle: {
    ...body.sm.medium,
    color: primaryColors.gray[700],
  },
  valueStyle: {
    color: primaryColors.gray[900],
    ...body.sm.regular,
    // width: "100%",
    flex: 1,
  },
  placeholderStyle: {
    ...body.sm.regular,
    color: primaryColors.gray[500],
    backgroundColor: "#fff",
  },
  inputContainerStyle: {
    borderBottomWidth: 0,
    width: "100%",
  },
  descriptionTriggerStyle: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    borderColor: primaryColors.gray[300],
    borderWidth: SW(1),
    borderRadius: SW(8),
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
    paddingHorizontal: SW(14),
    paddingVertical: SH(1),
    height: SH(96),
  },
  multiselectTriggerStyle: {
    width: SW(SCREEN_WIDTH * (1 / 4.5)),
  },
  multiSelectPlaceholderStyle: {
    ...body.sm.regular,
    color: primaryColors.button.active,
    flex: 0,
  },
  attachFilesTriggerStyle: {
    display: "flex",
    flexDirection: "column",
    borderColor: primaryColors.gray[400],
    borderWidth: SW(1),
    borderRadius: SW(8),
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingHorizontal: SW(44),
    paddingVertical: SH(16),
    gap: SW(8),
    borderStyle: "dashed",
  },
  attachFilesPlaceholderStyle1: {
    ...body.sm.regular,
    color: primaryColors.brand[1000],
  },
  attachFilesPlaceholderStyle2: {
    ...body.sm.regular,
    color: primaryColors.gray[900],
  },
  dropdownOptionsItemContainerStyle: {
    // flexDirection: "row",
    // alignItems: "center",
    // paddingVertical: 12,
    // borderRadius: 8,
    // backgroundColor: "#f5f5f5",
    // height: 40,
    // paddingHorizontal: 0,
    // marginVertical: 6,
    // marginHorizontal: 4,
  },
  dropdownOptionsContainerStyle: {
    borderRadius: SW(8),
    backgroundColor: "white",
    borderWidth: 0,
    maxHeight: DROPDOWN_HEIGHT,
    minHeight: DROPDOWN_HEIGHT,
    minWidth: DROPDOWN_WIDTH,
    maxWidth: DROPDOWN_WIDTH,
    padding: SW(16),
  },
  dropdownOptionsSearchStyle: {
    borderRadius: SW(8),
    minWidth: "100%",
    alignSelf: "center",
    borderColor: primaryColors.brand[1000],
    height: SH(44),
    ...body.md.regular,
  },
  placeholderColor: primaryColors.gray[500],
  floatingButton: {
    borderRadius: SW(12),
    height: SH(40),
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetInput: {
    borderBottomWidth: SW(1),
  },
  bottomSheetDescription: {
    borderBottomWidth: SW(1),
    height: SH(92),
    textAlignVertical: "top",
  },
  bottomButtonContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SH(12),
    gap: SW(10),
    borderColor: primaryColors.gray[200],
    borderTopWidth: SW(1),
    paddingHorizontal: SW(20),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -SH(0.5) },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 10, // minimal shadow for Android
    backgroundColor: "#fff",
    width: "100%",
  },
  approveButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: SH(6),
    paddingRight: SW(8),
    paddingLeft: SW(4),
    borderRadius: SW(8),
    borderColor: primaryColors.success[600],
    borderWidth: SW(1),
    gap: SW(2), // spacing between icon & text
  },
  rejectButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: SH(6),
    paddingRight: SW(8),
    paddingLeft: SW(6),
    borderRadius: SW(8),
    borderColor: primaryColors.error[600],
    borderWidth: StyleSheet.hairlineWidth,
    gap: SW(4),
  },
  minimalShadowDown: {
    elevation: 1,
    shadowColor: "#0A0D12",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  minimalShadowUp: {
    elevation: 0, // Android still only draws downward shadows
    shadowColor: "#0A0D12",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
};
