import { primaryColors, secondaryColors } from "./colors";
import { body } from "./typography";
import { Dimensions, StyleSheet, TextStyle, ViewStyle } from "react-native";
const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get("window");
const DROPDOWN_HEIGHT = SCREEN_HEIGHT * 0.5;
const DROPDOWN_WIDTH = SCREEN_WIDTH * 0.7;
export const formElementsStyles: Record<
  string,
  ViewStyle | { color: string } | string | TextStyle
> = {
  triggerStyle: {
    display: "flex",
    flexDirection: "row",
    maxWidth: "100%",
    borderColor: secondaryColors.gray[200],
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
    height: 44,
  },
  disabledStyle: {
    backgroundColor: secondaryColors.gray[50],
  },
  titleStyle: {
    ...body.sm.medium,
    color: secondaryColors.gray[700],
  },
  valueStyle: {
    color: secondaryColors.gray[900],
    ...body.sm.regular,
    // width: "100%",
    flex: 1,
  },
  placeholderStyle: {
    ...body.sm.regular,
    color: secondaryColors.gray[500],
    backgroundColor: "#fff",
  },
  inputContainerStyle: {
    borderBottomWidth: 0,
    width: "100%",
  },
  descriptionTriggerStyle: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    borderColor: secondaryColors.gray[300],
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 1,
    height: 96,
  },
  multiselectTriggerStyle: {
    width: SCREEN_WIDTH * (1 / 4.5),
  },
  multiSelectPlaceholderStyle: {
    ...body.sm.regular,
    color: primaryColors.brand[900],
    flex: 0,
  },
  attachFilesTriggerStyle: {
    display: "flex",
    flexDirection: "column",
    borderColor: secondaryColors.gray[400],
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingHorizontal: 44,
    paddingVertical: 16,
    gap: 8,
    borderStyle: "dashed",
  },
  attachFilesPlaceholderStyle1: {
    ...body.sm.regular,
    color: primaryColors.brand[900],
  },
  attachFilesPlaceholderStyle2: {
    ...body.sm.regular,
    color: secondaryColors.gray[900],
  },
  dropdownOptionsItemContainerStyle: {
    // flexDirection: "row",
    // alignItems: "center",
    // paddingVertical: 12,
    // borderRadius: 8,
    // backgroundColor: "#f5f5f5",
    // height: 40,
    // paddingHorizontal: 0,
    // marginVertical: 6,
    // marginHorizontal: 4,
  },
  dropdownOptionsContainerStyle: {
    borderRadius: 8,
    backgroundColor: "white",
    borderWidth: 0,
    maxHeight: DROPDOWN_HEIGHT,
    minHeight: DROPDOWN_HEIGHT,
    minWidth: DROPDOWN_WIDTH,
    maxWidth: DROPDOWN_WIDTH,
    padding: 16,
  },
  dropdownOptionsSearchStyle: {
    borderRadius: 8,
    minWidth: "100%",
    alignSelf: "center",
    borderColor: primaryColors.brand[900],
    height: 44,
    ...body.md.regular,
  },
  placeholderColor: secondaryColors.gray[500],
  floatingButton: {
    borderRadius: 12,
    height: 40,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetInput: {
    borderBottomWidth: 1,
  },
  bottomSheetDescription: {
    borderBottomWidth: 1,
    height: 92,
    textAlignVertical: "top",
  },
  bottomButtonContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    gap: 10,
    borderColor: secondaryColors.gray[200],
    borderTopWidth: 1,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -0.5 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 10, // minimal shadow for Android
    backgroundColor: "#fff",
    width: "100%",
  },
  approveButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
    paddingRight: 8,
    paddingLeft: 4,
    borderRadius: 8,
    borderColor: primaryColors.success[600],
    borderWidth: 1,
    gap: 2, // spacing between icon & text
  },
  rejectButton: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
    paddingRight: 8,
    paddingLeft: 6,
    borderRadius: 8,
    borderColor: primaryColors.error[600],
    borderWidth: StyleSheet.hairlineWidth,
    gap: 4,
  },
  minimalShadowDown: {
    elevation: 1,
    shadowColor: "#0A0D12",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  minimalShadowUp: {
    elevation: 0, // Android still only draws downward shadows
    shadowColor: "#0A0D12",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
};
